### ISSUE TITLE
Allow multiple actions to map to same simplesource command topic(s)

### ISSUE THREAD

**Issue by wongelz** [simplesourcing/simplesagas#9]
Consider the following **SourcingApp** setup:

```
CommandSpec<GenericRecord, CreateReservationSubSaga, AccountKey, AccountCommand> createReservationSpec;

CommandSpec<GenericRecord, ConfirmReservationSubSaga, AccountKey, AccountCommand> confirmReservationSpec;

...

new SourcingApp<>(
        AvroSerdes.actionSerdes(AppShared.SCHEMA_REGISTRY_URL, false), builder ->
        ...
).addCommand(createReservationSpec, builder ->
        builder
                .withTopicNamer(TopicNamer.forPrefix("auction_avro_", "account"))
                .withDefaultConfig(6, 1, 7)
).addCommand(confirmReservationSpec, builder ->
        builder
                .withTopicNamer(TopicNamer.forPrefix("auction_avro_", "account"))
                .withDefaultConfig(6, 1, 7)
)
```

This results in the following exception:
```
Exception in thread "main" org.apache.kafka.streams.errors.TopologyException: Invalid topology: Topic auction_avro_account-command_response has already been registered by another source.
	at org.apache.kafka.streams.processor.internals.InternalTopologyBuilder.validateTopicNotAlreadyRegistered(InternalTopologyBuilder.java:569)
	at org.apache.kafka.streams.processor.internals.InternalTopologyBuilder.addSource(InternalTopologyBuilder.java:389)
	at org.apache.kafka.streams.kstream.internals.InternalStreamsBuilder.stream(InternalStreamsBuilder.java:48)
	at org.apache.kafka.streams.StreamsBuilder.stream(StreamsBuilder.java:137)
	at org.apache.kafka.streams.StreamsBuilder.stream(StreamsBuilder.java:97)
	at io.simplesource.saga.action.sourcing.CommandConsumer.commandResponseStream(CommandConsumer.java:21)
	at io.simplesource.saga.action.sourcing.SourcingApp.lambda$addCommand$0(SourcingApp.java:58)
	at io.simplesource.saga.action.sourcing.SourcingApp.run(SourcingApp.java:118)
	at io.simplesource.example.auction.server.SagaActionProcessorApp.main(SagaActionProcessorApp.java:109)
```

**Comment by szoio** [comment]
This is a general limitation of the Kafka streams.
When defining a topology, you can only one stream from a source topic (i.e. where the stream is created from the topic).
One solution (maybe you can call this a workaround) is to make a single action for the aggregate and make that polymorphic. So in this case have an account command that handles create and confirm reservation, and other account operations.
